"""added_borrow_record

Revision ID: 0cc2df234ea0
Revises: d2acdb69e35c
Create Date: 2026-08-30 16:56:11.772852

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc2df234ea0"
down_revision: str | Sequence[str] | None = "d2acdb69e35c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "borrowrecord",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("reader_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reader_id"],
            ["reader.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_borrowrecord_book_id"), "borrowrecord", ["book_id"], unique=False)
    op.create_index(op.f("ix_borrowrecord_reader_id"), "borrowrecord", ["reader_id"], unique=False)

    op.execute(
        """
        CREATE TRIGGER set_borrow_record_updated_at
        BEFORE UPDATE ON borrowrecord
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS set_borrow_record_updated_at ON book;")
    op.drop_index(op.f("ix_borrowrecord_reader_id"), table_name="borrowrecord")
    op.drop_index(op.f("ix_borrowrecord_book_id"), table_name="borrowrecord")
    op.drop_table("borrowrecord")
    # ### end Alembic commands ###
